# Generated by Django 4.1.7 on 2024-06-11 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eleicoes_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='eleicao',
            name='ativa',
            field=models.BooleanField(default=False),
        ),
    ]
